version: '3'
services:
  samba:
    build: build
    image: lowet84/samba
    network_mode: "host"
    restart: always
    command: sh start.sh
    volumes:
      - /mnt/filer/Settings/samba/smb.conf:/etc/samba/smb.conf
      - /mnt/filer/:/data
