version: '3'
services:
  drone-server:
    image: drone/drone:0.8.1
    restart: always
    environment:
      - DRONE_GITHUB=true
    env_file: 
      - ${SETTINGS_PATH}/drone/secrets.env
    volumes:
      - ${SETTINGS_PATH}/drone:/var/lib/drone/
    labels:
      - traefik.enable=true
      - traefik.backend=drone-server
      - traefik.frontend.passHostHeader=true
      - traefik.port=8000
      - traefik.frontend.rule=Host:drone.local
      - traefik.docker.network=homeserver2
    networks:
      - drone
      - homeserver2

  drone-agent:
    image: drone/agent:0.8.1
    command: agent
    restart: always
    depends_on: [ drone-server  ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_GITHUB=true
    env_file: ${SETTINGS_PATH}/drone/secrets.env
    networks:
      - drone

networks:
  drone:
  homeserver2:
    external: true
