version: '2'

services:
  sabnzbd:
    image: linuxserver/sabnzbd
    volumes:
      - /mnt/filer/Downloads:/data/Downloads
      - /mnt/filer/Film:/data/Film
      - /mnt/filer/Settings/sabnzbd:/config
    restart: always
    networks:
      - homeserver2
    environment:
     - PUID=0
     - PGID=0
    labels:
      - traefik.enable=true
      - traefik.backend=sabnzbd 
      - traefik.frontend.passHostHeader=true
      - traefik.port=8080
      - traefik.frontend.rule=Host:sabnzbd.local

  sonarr:
    image: linuxserver/sonarr
    volumes:
     - /dev/rtc:/dev/rtc:ro
     - /mnt/filer/Settings/sonarr:/config
     - /mnt/filer/Rar2fs/Downloads:/data/Downloads
     - /mnt/filer/Rar2fs/TV:/data/TV
     - /mnt/filer/Rar2fs/TVCharlotte:/data/TVCharlotte
     - /mnt/filer/Anime:/data/Anime
    restart: always
    networks:
      - homeserver2
    environment:
     - PUID=0
     - GUID=0 
    labels:
      - traefik.enable=true
      - traefik.backend=sonarr
      - traefik.frontend.passHostHeader=true
      - traefik.port=8989
      - traefik.frontend.rule=Host:sonarr.local
  
#  deluge:
#    image: linuxserver/deluge
#    restart: always
#    networks:
#      - homeserver2
#    environment:
#     - PUID=0
#     - GUID=0
#     - TZ=SE
#    labels:
#      - traefik.enable=true
#      - traefik.backend=deluge
#      - traefik.frontend.passHostHeader=true
#      - traefik.port=8112
#      - traefik.frontend.rule=Host:deluge.local
#    volumes:
#      - /mnt/filer/Settings/deluge:/config
#      - /mnt/filer/:/data

  plex:
    image: linuxserver/plex
    ports:
     - 32400:32400
    environment:
     - PUID=0
     - GUID=0
     - TZ=SE
    restart: always
    network_mode: "host"
    volumes:
      - /mnt/filer/Settings/plex:/config
      - /mnt/filer/Rar2fs:/data

  radarr:
    image: linuxserver/radarr
    volumes:
     - /dev/rtc:/dev/rtc:ro
     - /mnt/filer/Settings/radarr:/config
     - /mnt/filer/Rar2fs/Downloads:/data/Downloads
     - /mnt/filer/Rar2fs/Film:/data/Film
    restart: always
    networks:
      - homeserver2
    environment:
     - PUID=0
     - GUID=0
    labels:
      - traefik.enable=true
      - traefik.backend=radarr
      - traefik.frontend.passHostHeader=true
      - traefik.port=7878
      - traefik.frontend.rule=Host:radarr.local

networks:
  homeserver2:
    external: true
