version: '3'

services:
  sabnzbd:
    image: linuxserver/sabnzbd
    volumes:
      - ${FILES_PATH}/Downloads:/data/Downloads
      - ${FILES_PATH}/Film:/data/Film
      - ${SETTINGS_PATH}/sabnzbd:/config
    restart: always
    networks:
      - homeserver2
    environment:
     - PUID=0
     - PGID=0
    labels:
      - traefik.enable=true
      - traefik.backend=sabnzbd 
      - traefik.frontend.passHostHeader=true
      - traefik.port=8080
      - traefik.frontend.rule=Host:sabnzbd.${HOMESERVER_DOMAIN}

  sonarr:
    image: linuxserver/sonarr
    volumes:
     - /dev/rtc:/dev/rtc:ro
     - ${SETTINGS_PATH}/sonarr:/config
     - ${RAR2FS_PATH}/Downloads:/data/Downloads
     - ${RAR2FS_PATH}/TV:/data/TV
     - ${RAR2FS_PATH}/TVCharlotte:/data/TVCharlotte
     - ${FILES_PATH}/Anime:/data/Anime
    restart: always
    networks:
      - homeserver2
    environment:
     - PUID=0
     - GUID=0 
    labels:
      - traefik.enable=true
      - traefik.backend=sonarr
      - traefik.frontend.passHostHeader=true
      - traefik.port=8989
      - traefik.frontend.rule=Host:sonarr.${HOMESERVER_DOMAIN}

  plex:
    image: linuxserver/plex
    ports:
     - 32400:32400
    environment:
     - PUID=0
     - GUID=0
     - TZ=SE
    restart: always
    network_mode: "host"
    volumes:
      - ${SETTINGS_PATH}/plex:/config
      - ${RAR2FS_PATH}:/data

  radarr:
    image: linuxserver/radarr
    volumes:
     - /dev/rtc:/dev/rtc:ro
     - ${SETTINGS_PATH}/radarr:/config
     - ${RAR2FS_PATH}/Downloads:/data/Downloads
     - ${RAR2FS_PATH}/Film:/data/Film
    restart: always
    networks:
      - homeserver2
    environment:
     - PUID=0
     - GUID=0
    labels:
      - traefik.enable=true
      - traefik.backend=radarr
      - traefik.frontend.passHostHeader=true
      - traefik.port=7878
      - traefik.frontend.rule=Host:radarr.${HOMESERVER_DOMAIN}

networks:
  homeserver2:
    external: true
