version: '3'
services:
  mysql:
    image: mysql:5.6
    env_file: parameters.env
    volumes:
      - ${SETTINGS_PATH}/simpleci/mysql:/var/lib/mysql
    networks:
      - simpleci

  rabbitmq:
    image: rabbitmq:latest
    volumes:
      - ${SETTINGS_PATH}/simpleci/rabbitmq:/var/lib/rabbitmq
    networks:
      - simpleci

  redis:
    image: redis:latest
    volumes:
      - ${SETTINGS_PATH}/simpleci/redis:/var/lib/redis
    networks:
      - simpleci

  dispatcher:
    image: simpleci/dispatcher
    env_file: parameters.env
    networks:
      - simpleci

  worker:
    image: simpleci/worker
    volumes:
      - ${SETTINGS_PATH}/simpleci/worker:/var/run/docker.sock
    env_file: parameters.env
    networks:
      - simpleci

  simpleci-frontend:
    image: simpleci/frontend
    volumes:
      - ${SETTINGS_PATH}/simpleci/frontend:/var/log/simpleci
    labels:
      - traefik.enable=true
      - traefik.backend=simpleci-frontend
      - traefik.frontend.passHostHeader=true
      - traefik.port=80
      - traefik.frontend.rule=Host:simpleci.${HOMESERVER_DOMAIN}
      - traefik.docker.network=homeserver2
    env_file: parameters.env
    networks:
      - simpleci
      - homeserver2

networks:
  simpleci:
  homeserver2:
    external: true
