version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts-alpine
    restart: always 
    volumes:
      - ${SETTINGS_PATH}/jenkins:/var/jenkins_home
    labels:
      - traefik.enable=true
      - traefik.backend=jenkins
      - traefik.frontend.passHostHeader=true
      - traefik.port=8080
      - traefik.frontend.rule=Host:jenkins.${HOMESERVER_DOMAIN}
    networks:
      - homeserver2

networks:
  homeserver2:
    external: true
