version: '3'
services:
  when:
    image: lowet84/when 
    restart: always
    labels:
      - traefik.enable=true
      - traefik.backend=when
      - traefik.frontend.passHostHeader=true
      - traefik.port=7000
      - traefik.frontend.rule=Host:when.local
    networks:
      - homeserver2
    environment:
      - DATABASE=rethinkdb
      - DEVUSER=dev

networks:
  homeserver2:
    external: true
