version: '3'
services:
  rethinkdb:
    image: rethinkdb
    ports:
      - 28015:28015
    restart: always
    command: rethinkdb --bind all
    labels:
      - traefik.enable=true
      - traefik.backend=rethinkdb
      - traefik.frontend.passHostHeader=true
      - traefik.port=8080
      - traefik.frontend.rule=Host:rethinkdb.${HOMESERVER_DOMAIN}
    volumes:
      - ${SETTINGS_PATH}/rethinkdb:/data
    networks:
      - homeserver2

networks:
  homeserver2:
    external: true
