version: '3'
services:
  mysql:
    image: mysql
    restart: always
    volumes:
      - ${SETTINGS_PATH}/guacamole:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: gurkburk
    labels:
      - traefik.enable=false
    networks:
      - guacamole

  mysql-init:
    image: lowet84/mysql-guacamole-init
    build: init/
    volumes:
     - ${SETTINGS_PATH}/guacamole:/data
    environment:
      PASSWORD: gurkburk
    labels:
      - traefik.enable=false
    networks:
      - guacamole

  guacd:
    image: glyptodon/guacd
    restart: always
    labels:
      - traefik.enable=false
    networks:
      - guacamole

  guacamole:
    image: lowet84/guacamole
    restart: always
    networks:
      - guacamole
      - homeserver2
    environment:
      GUACD_HOSTNAME: guacd
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: guacamole_password
      MYSQL_HOSTNAME: mysql
      GUACD_PORT_4822_TCP_ADDR: guacd
      GUACD_PORT_4822_TCP_PORT: 4822
    labels:
#      - traefik.enable=true
      - traefik.backend=guacamole
      - traefik.frontend.passHostHeader=true
      - traefik.port=8080
      - traefik.docker.network=homeserver2
      - traefik.frontend.rule=Host:guacamole.${HOMESERVER_DOMAIN}    

networks:
  guacamole:
  homeserver2:
    external: true
