version: '3'
services:
  mysql:
    image: mysql
    restart: always
    volumes:
      - ${SETTINGS_PATH}/guacamole-alpine:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: gurkburk
    networks:
      - guacamole-alpine

  mysql-init:
    image: lowet84/mysql-guacamole-init:alpine
    volumes:
     - ${SETTINGS_PATH}/guacamole-alpine:/data
    environment:
      PASSWORD: gurkburk
    networks:
      - guacamole-alpine

  guacd:
    image: glyptodon/guacd
    restart: always
    networks:
      - guacamole-alpine

  guacamole-alpine:
    image: lowet84/guacamole:alpine
    restart: always
    networks:
      - guacamole-alpine
      - homeserver2
    labels:
      - traefik.enable=true
      - traefik.backend=guacamole-alpine
      - traefik.frontend.passHostHeader=true
      - traefik.port=8080
      - traefik.frontend.rule=Host:guacamole-alpine.${HOMESERVER_DOMAIN}
      - traefik.docker.network=homeserver2
    environment:
      GUACD_HOSTNAME: guacd
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: guacamole_password
      MYSQL_HOSTNAME: mysql
      GUACD_PORT_4822_TCP_ADDR: guacd
      GUACD_PORT_4822_TCP_PORT: 4822

networks:
  guacamole-alpine:
  homeserver2:
    external: true
