version: '3'
services:
  traefik:
    image: traefik
    ports:
      - 80:80
    restart: always
    labels:
      - traefik.enable=true
      - traefik.backend=traefik
      - traefik.frontend.passHostHeader=true
      - traefik.port=8080
      - traefik.frontend.rule=Host:traefik.${HOMESERVER_DOMAIN}
    command: --web --docker --logLevel=DEBUG
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - homeserver2    

  public:
    image: traefik
    restart: always
    ports: 
      - 31080:80
      - 443:443
    labels:
#      - traefik.enable=true
#      - traefik.backend=public
#      - traefik.frontend.passHostHeader=true
      - traefik.port=8080
      - traefik.frontend.rule=Host:traefik-public.${HOMESERVER_DOMAIN}
    command: --web --logLevel=DEBUG --configfile=/config/traefik-public.toml
    volumes:
      - ${SETTINGS_PATH}/traefik:/config
    networks:
      - homeserver2

networks:
  homeserver2:
    external: true
        
