version: '2'
services:
  traefik:
    image: traefik
    ports:
      - 8080:8080
      - 80:80
    restart: always
    labels:
      - traefik.enable=true
      - traefik.backend=traefik
      - traefik.frontend.passHostHeader=true
      - traefik.port=8080
      - traefik.frontend.rule=Host:traefik.local
    command: --web --docker --logLevel=DEBUG --docker.exposedbydefault=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
