version: '3'
services:
  traefik:
    image: traefik:1.5.1-alpine
    restart: always
    labels:
      - traefik.backend=traefik
      - traefik.frontend.passHostHeader=true
      - traefik.port=8080
      - traefik.frontend.rule=Host:traefik.${HOMESERVER_DOMAIN}
    command: --web --logLevel=DEBUG --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - homeserver2    

  public:
    image: traefik:1.5.1-alpine
    restart: always
    ports: 
      - 80:80
      - 443:443
    labels:
      - traefik.backend=public
      - traefik.frontend.passHostHeader=true
      - traefik.port=8080
      - traefik.frontend.rule=Host:ptraefik.${HOMESERVER_DOMAIN}
    command: --web --logLevel=DEBUG --configfile=/config/traefik-public.toml --docker.exposedbydefault=false
    volumes:
      - ${SETTINGS_PATH}/traefik:/config
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - homeserver2

networks:
  homeserver2:
    external: true
        
