version: '3'
services:
  nextcloud:
    image: nextcloud
    restart: always
    networks:
      - homeserver2
      - nextcloud
    volumes:
     - ${SETTINGS_PATH}/nextcloud/html:/var/www/html

  db:
    image: mariadb
    restart: always
    volumes:
      - ${SETTINGS_PATH}/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - nextcloud

networks:
  homeserver2:
    external: true
  nextcloud:
