version: '3'
services:
  nextcloud:
    image: nextcloud
    restart: always
    networks:
      - homeserver2
      - nextcloud
    volumes:
     - ${SETTINGS_PATH}/nextcloud/html:/var/www/html
    labels:
      - traefik.enable=true
      - traefik.backend=nextcloud
      - traefik.frontend.passHostHeader=true
      - traefik.port=80
      - traefik.docker.network=homeserver2
      - traefik.frontend.rule=Host:nextcloud.${HOMESERVER_DOMAIN}

  db:
    image: mariadb
    restart: always
    volumes:
      - ${SETTINGS_PATH}/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - nextcloud
    labels:
      - traefik.enable=false

networks:
  homeserver2:
    external: true
  nextcloud:
