version: '3'

services:
  backup:
    image: lowet84/backup
    volumes:
      - ${SETTINGS_PATH}:/settings
      - ${BACKUP_PATH}:/backup
    networks:
      - homeserver2
    

networks:
  homeserver2:
    external: true
