version: '2'

services:
  db:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: filerun
      MYSQL_USER: filerun
      MYSQL_PASSWORD: filerun
      MYSQL_DATABASE: filerun
    volumes:
      - ${SETTINGS_PATH}/filerun/db:/var/lib/mysql

  web:
    depends_on:
      - db
    links:
      - db
    image: afian/filerun
    ports:
      - "8090:80"
    volumes:
      - ${SETTINGS_PATH}/filerun/html:/var/www/html
      - ${FILES_PATH}:/user-files
