version: '3'
services:
  nodered:
#    image: nodered/node-red-docker:slim
    build: .
    restart: always
    volumes:
      - ${SETTINGS_PATH}/nodered:/data
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    networks:
      - homeserver2
    labels:
      - traefik.enable=true
      - traefik.backend=nodered
      - traefik.frontend.passHostHeader=true
      - traefik.port=1880
      - traefik.frontend.rule=Host:nodered.${HOMESERVER_DOMAIN}

networks:
  homeserver2:
    external: true
