version: '3'
services:
  resume:
    image: lowet84/resume
    restart: always
    labels:
      - traefik.enable=true
      - traefik.backend=resume
      - traefik.frontend.passHostHeader=true
      - traefik.port=7000
      - traefik.frontend.rule=Host:resume.local
    networks:
      - homeserver2
    environment:
      - DATABASE=rethinkdb
      - RESET=true

networks:
  homeserver2:
    external: true
