version: '3'
services:
  resume:
    image: lowet84/resume
    restart: always
    networks:
      - homeserver2
    environment:
      - DATABASE=rethinkdb
      - RESET=true

networks:
  homeserver2:
    external: true
