version: '3'
services:
  pwa:
    image: lowet84/pwa-template
    restart: always
    networks:
      - homeserver2
    labels:
      - traefik.enable=true
      - traefik.backend=pwa
      - traefik.frontend.passHostHeader=true
      - traefik.port=7000
      - traefik.frontend.rule=Host:pwa.${HOMESERVER_DOMAIN}
    environment:
      - DATABASE=rethinkdb
      - DATAPATH=/data
    volumes:
     - ${FILES_PATH}/Audiobooks:/data

networks:
  homeserver2:
    external: true
