version: '2'
services:
  portainer:
    image: portainer/portainer
    restart: always
    volumes: 
     - /var/run/docker.sock:/var/run/docker.sock
     - /mnt/filer/Settings/portainer:/data
    networks:
      - homeserver2
    labels:
      - traefik.enable=true
      - traefik.backend=portainer
      - traefik.frontend.passHostHeader=true
      - traefik.port=9000
      - traefik.frontend.rule=Host:portainer.local

networks:
  homeserver2:
    external: true    
