version: '3'
services:
  portainer:
    image: portainer/portainer
    restart: always
    volumes: 
     - /var/run/docker.sock:/var/run/docker.sock
     - ${SETTINGS_PATH}/portainer:/data
    command: --no-auth
    networks:
      - homeserver2
    labels:
      - traefik.enable=true
      - traefik.backend=portainer
      - traefik.frontend.passHostHeader=true
      - traefik.port=9000
      - traefik.frontend.rule=Host:portainer.${HOMESERVER_DOMAIN}

networks:
  homeserver2:
    external: true    
