version: '3'
services:
  delugevpn:
    image: lowet84/delugevpn
    cap_add:
      - NET_ADMIN
    volumes:
      - ${SETTINGS_PATH}/delugevpn/vpn:/etc/openvpn
      - ${SETTINGS_PATH}/delugevpn/deluge:/config
      - ${FILES_PATH}:/data
    devices:
      - /dev/net/tun
    labels:
      - traefik.enable=true
      - traefik.backend=delugevpn
      - traefik.frontend.passHostHeader=true
      - traefik.port=8112
      - traefik.frontend.rule=Host:delugevpn.${HOMESERVER_DOMAIN}
    networks:
      - homeserver2

networks:
  homeserver2:
    external: true    

