version: '3.4'
services:
  delugevpn:
    image: lowet84/delugevpn
    cap_add:
      - NET_ADMIN
    volumes:
      - ${SETTINGS_PATH}/delugevpn/vpn:/etc/openvpn
      - ${SETTINGS_PATH}/delugevpn/deluge:/config
      - ${FILES_PATH}:/data
    devices:
      - /dev/net/tun
    labels:
      - traefik.enable=true
      - traefik.backend=delugevpn
      - traefik.frontend.passHostHeader=true
      - traefik.port=8112
      - traefik.frontend.rule=Host:delugevpn.${HOMESERVER_DOMAIN}
      - traefik.docker.network=homeserver2
    healthcheck:
      test: ["CMD", "sh", "/health.sh"]
      interval: 1m
      timeout: 30s
      retries: 3
      start_period: 30s
    networks:
      - homeserver2

networks:
  homeserver2:
    external: true    

