version: '3'
services:
  gogs:
    image: gogs/gogs
    restart: always
    volumes:
      - ${SETTINGS_PATH}/gogs:/data
    networks:
      - homeserver2
    labels:
      - traefik.enable=true
      - traefik.backend=gogs
      - traefik.frontend.passHostHeader=true
      - traefik.port=3000
      - traefik.frontend.rule=Host:gogs.${HOMESERVER_DOMAIN}

networks:
  homeserver2:
    external: true
